spring:
  application:
    name: MyVehicleLogger
  web:
    resources:
      static-locations: file:///D:/Nextcloud/IdeaProjects/MyVehicleLogger/vehicle_image/
  datasource:
    url: "jdbc:mysql://localhost:3306/my_vehicle_logger?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800

file:
  upload-dir: D:/Nextcloud/IdeaProjects/MyVehicleLogger/vehicle_image/
  access-url: http://localhost:8080/images/
