spring:
  application:
    name: MyVehicleLogger
  profiles:
    active: dev
  datasource:
    url: "jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:my_vehicle_logger}?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800

app:
  cors:
    allowed-origins: "https://my-vehicle-logger.online", "http://localhost:5173/"