name: Deploy to Amazon Elastic Beanstalk

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::034333502474:role/GitHubActions-EB-Deploy-Role
        aws-region: eu-north-1

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with: 
        maven-version: 3.9.11

    - name: Set up JDK
      uses: actions/setup-java@v4
      with: 
        distribution: temurin
        java-version: '21'

    - name: Build JAR
      run: mvn clean package

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
          application_name: my-vehicle-logger
          environment_name: My-vehicle-logger-env-1
          version_label: ${{ github.sha }}
          region: eu-north-1
          deployment_package: target/*.jar       
